function perf_theta = RBTheta_252(mu)
%RBTHETA_252
%    PERF_THETA = RBTHETA_252(L,L_0,R,R_0)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-Nov-2020 12:33:22
rho_C_t = mu("rho_C_t");
rho_C_b = mu("rho_C_b");
k_b = mu("k_b");
k_t = mu("k_t");
h = mu("h");
d = mu("d");
l_0 = mu("l_0");
r_0 = mu("r_0");
l = mu("l");
r = mu("r");
L = mu("L");
omega_p = omega_of_r_final(r_0);

perf_theta = (l_0.*1.0./r.^2.*r_0.^2.*omega_p*rho_C_b)./l;%use the function omega_of_r_reg1em8(r_0) insteady of omega_p
