function one = RBTheta_253(mu)
%RBTHETA_253
%    ONE = RBTHETA_253

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-Nov-2020 12:33:22
rho_C_t = mu("rho_C_t");
rho_C_b = mu("rho_C_b");
k_b = mu("k_b");
k_t = mu("k_t");
h = mu("h");
d = mu("d");
l_0 = mu("l_0");
r_0 = mu("r_0");
l = mu("l");
r = mu("r");
L = mu("L");

one = 1.0;
