/**
  * The structures are defined for an elliptic PDE with the following restrictions:
  *  1. The number of thetas is equal to one (T1).
  *  2. The problem contains one load vector (F1) and one output (O1).
  *
  * The structures defined are:
  * 1. Theta --> parameter-dependent part of the PDE
  * 2. RBThetaExpansion
  */

///-------------------------------------------------------------------------
#ifndef DWARFELEPHANTGEOM3DRBTHETAEXPANSION_RFA_H
#define DWARFELEPHANTGEOM3DRBTHETAEXPANSION_RFA_H

///---------------------------------INCLUDES--------------------------------
// libMesh includes (RB package)
#include "libmesh/rb_theta.h"
#include "libmesh/rb_assembly_expansion.h"

#include "DwarfElephantGeom3DRBTheta_RFA.h"
// Forward Declarations
namespace libMesh
{
  class RBThetaExpansion;
}
///----------------------------RBTHETAEXPANSION-----------------------------
/**
 * Attaches the stiffness matrix and the theta object to a structure of the
 * type RBThetatExpansion.
 *
 */

struct Geom3DRBThetaExpansion : RBThetaExpansion
{
  Geom3DRBThetaExpansion()
  {
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxX1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxX2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxX3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxX4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_maxX5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minY1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minY2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minY3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minY4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minY5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minZ1_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minZ2_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minZ3_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minZ4_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_minZ5_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_VesselCyl_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXX_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXY_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionXZ_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYX_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYY_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionYZ_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZX_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZY_BoundingBox_0);
  attach_A_theta(&Geom3DRB_ATheta_DiffusionZZ_BoundingBox_0);
  attach_A_theta(&_rb_theta);
}
  Geom3DRB_ATheta_DiffusionXX_maxZ1 Geom3DRB_ATheta_DiffusionXX_maxZ1_0;
  Geom3DRB_ATheta_DiffusionXY_maxZ1 Geom3DRB_ATheta_DiffusionXY_maxZ1_0;
  Geom3DRB_ATheta_DiffusionXZ_maxZ1 Geom3DRB_ATheta_DiffusionXZ_maxZ1_0;
  Geom3DRB_ATheta_DiffusionYX_maxZ1 Geom3DRB_ATheta_DiffusionYX_maxZ1_0;
  Geom3DRB_ATheta_DiffusionYY_maxZ1 Geom3DRB_ATheta_DiffusionYY_maxZ1_0;
  Geom3DRB_ATheta_DiffusionYZ_maxZ1 Geom3DRB_ATheta_DiffusionYZ_maxZ1_0;
  Geom3DRB_ATheta_DiffusionZX_maxZ1 Geom3DRB_ATheta_DiffusionZX_maxZ1_0;
  Geom3DRB_ATheta_DiffusionZY_maxZ1 Geom3DRB_ATheta_DiffusionZY_maxZ1_0;
  Geom3DRB_ATheta_DiffusionZZ_maxZ1 Geom3DRB_ATheta_DiffusionZZ_maxZ1_0;
  Geom3DRB_ATheta_DiffusionXX_maxZ2 Geom3DRB_ATheta_DiffusionXX_maxZ2_0;
  Geom3DRB_ATheta_DiffusionXY_maxZ2 Geom3DRB_ATheta_DiffusionXY_maxZ2_0;
  Geom3DRB_ATheta_DiffusionXZ_maxZ2 Geom3DRB_ATheta_DiffusionXZ_maxZ2_0;
  Geom3DRB_ATheta_DiffusionYX_maxZ2 Geom3DRB_ATheta_DiffusionYX_maxZ2_0;
  Geom3DRB_ATheta_DiffusionYY_maxZ2 Geom3DRB_ATheta_DiffusionYY_maxZ2_0;
  Geom3DRB_ATheta_DiffusionYZ_maxZ2 Geom3DRB_ATheta_DiffusionYZ_maxZ2_0;
  Geom3DRB_ATheta_DiffusionZX_maxZ2 Geom3DRB_ATheta_DiffusionZX_maxZ2_0;
  Geom3DRB_ATheta_DiffusionZY_maxZ2 Geom3DRB_ATheta_DiffusionZY_maxZ2_0;
  Geom3DRB_ATheta_DiffusionZZ_maxZ2 Geom3DRB_ATheta_DiffusionZZ_maxZ2_0;
  Geom3DRB_ATheta_DiffusionXX_maxZ3 Geom3DRB_ATheta_DiffusionXX_maxZ3_0;
  Geom3DRB_ATheta_DiffusionXY_maxZ3 Geom3DRB_ATheta_DiffusionXY_maxZ3_0;
  Geom3DRB_ATheta_DiffusionXZ_maxZ3 Geom3DRB_ATheta_DiffusionXZ_maxZ3_0;
  Geom3DRB_ATheta_DiffusionYX_maxZ3 Geom3DRB_ATheta_DiffusionYX_maxZ3_0;
  Geom3DRB_ATheta_DiffusionYY_maxZ3 Geom3DRB_ATheta_DiffusionYY_maxZ3_0;
  Geom3DRB_ATheta_DiffusionYZ_maxZ3 Geom3DRB_ATheta_DiffusionYZ_maxZ3_0;
  Geom3DRB_ATheta_DiffusionZX_maxZ3 Geom3DRB_ATheta_DiffusionZX_maxZ3_0;
  Geom3DRB_ATheta_DiffusionZY_maxZ3 Geom3DRB_ATheta_DiffusionZY_maxZ3_0;
  Geom3DRB_ATheta_DiffusionZZ_maxZ3 Geom3DRB_ATheta_DiffusionZZ_maxZ3_0;
  Geom3DRB_ATheta_DiffusionXX_maxZ4 Geom3DRB_ATheta_DiffusionXX_maxZ4_0;
  Geom3DRB_ATheta_DiffusionXY_maxZ4 Geom3DRB_ATheta_DiffusionXY_maxZ4_0;
  Geom3DRB_ATheta_DiffusionXZ_maxZ4 Geom3DRB_ATheta_DiffusionXZ_maxZ4_0;
  Geom3DRB_ATheta_DiffusionYX_maxZ4 Geom3DRB_ATheta_DiffusionYX_maxZ4_0;
  Geom3DRB_ATheta_DiffusionYY_maxZ4 Geom3DRB_ATheta_DiffusionYY_maxZ4_0;
  Geom3DRB_ATheta_DiffusionYZ_maxZ4 Geom3DRB_ATheta_DiffusionYZ_maxZ4_0;
  Geom3DRB_ATheta_DiffusionZX_maxZ4 Geom3DRB_ATheta_DiffusionZX_maxZ4_0;
  Geom3DRB_ATheta_DiffusionZY_maxZ4 Geom3DRB_ATheta_DiffusionZY_maxZ4_0;
  Geom3DRB_ATheta_DiffusionZZ_maxZ4 Geom3DRB_ATheta_DiffusionZZ_maxZ4_0;
  Geom3DRB_ATheta_DiffusionXX_maxZ5 Geom3DRB_ATheta_DiffusionXX_maxZ5_0;
  Geom3DRB_ATheta_DiffusionXY_maxZ5 Geom3DRB_ATheta_DiffusionXY_maxZ5_0;
  Geom3DRB_ATheta_DiffusionXZ_maxZ5 Geom3DRB_ATheta_DiffusionXZ_maxZ5_0;
  Geom3DRB_ATheta_DiffusionYX_maxZ5 Geom3DRB_ATheta_DiffusionYX_maxZ5_0;
  Geom3DRB_ATheta_DiffusionYY_maxZ5 Geom3DRB_ATheta_DiffusionYY_maxZ5_0;
  Geom3DRB_ATheta_DiffusionYZ_maxZ5 Geom3DRB_ATheta_DiffusionYZ_maxZ5_0;
  Geom3DRB_ATheta_DiffusionZX_maxZ5 Geom3DRB_ATheta_DiffusionZX_maxZ5_0;
  Geom3DRB_ATheta_DiffusionZY_maxZ5 Geom3DRB_ATheta_DiffusionZY_maxZ5_0;
  Geom3DRB_ATheta_DiffusionZZ_maxZ5 Geom3DRB_ATheta_DiffusionZZ_maxZ5_0;
  Geom3DRB_ATheta_DiffusionXX_minX1 Geom3DRB_ATheta_DiffusionXX_minX1_0;
  Geom3DRB_ATheta_DiffusionXY_minX1 Geom3DRB_ATheta_DiffusionXY_minX1_0;
  Geom3DRB_ATheta_DiffusionXZ_minX1 Geom3DRB_ATheta_DiffusionXZ_minX1_0;
  Geom3DRB_ATheta_DiffusionYX_minX1 Geom3DRB_ATheta_DiffusionYX_minX1_0;
  Geom3DRB_ATheta_DiffusionYY_minX1 Geom3DRB_ATheta_DiffusionYY_minX1_0;
  Geom3DRB_ATheta_DiffusionYZ_minX1 Geom3DRB_ATheta_DiffusionYZ_minX1_0;
  Geom3DRB_ATheta_DiffusionZX_minX1 Geom3DRB_ATheta_DiffusionZX_minX1_0;
  Geom3DRB_ATheta_DiffusionZY_minX1 Geom3DRB_ATheta_DiffusionZY_minX1_0;
  Geom3DRB_ATheta_DiffusionZZ_minX1 Geom3DRB_ATheta_DiffusionZZ_minX1_0;
  Geom3DRB_ATheta_DiffusionXX_minX2 Geom3DRB_ATheta_DiffusionXX_minX2_0;
  Geom3DRB_ATheta_DiffusionXY_minX2 Geom3DRB_ATheta_DiffusionXY_minX2_0;
  Geom3DRB_ATheta_DiffusionXZ_minX2 Geom3DRB_ATheta_DiffusionXZ_minX2_0;
  Geom3DRB_ATheta_DiffusionYX_minX2 Geom3DRB_ATheta_DiffusionYX_minX2_0;
  Geom3DRB_ATheta_DiffusionYY_minX2 Geom3DRB_ATheta_DiffusionYY_minX2_0;
  Geom3DRB_ATheta_DiffusionYZ_minX2 Geom3DRB_ATheta_DiffusionYZ_minX2_0;
  Geom3DRB_ATheta_DiffusionZX_minX2 Geom3DRB_ATheta_DiffusionZX_minX2_0;
  Geom3DRB_ATheta_DiffusionZY_minX2 Geom3DRB_ATheta_DiffusionZY_minX2_0;
  Geom3DRB_ATheta_DiffusionZZ_minX2 Geom3DRB_ATheta_DiffusionZZ_minX2_0;
  Geom3DRB_ATheta_DiffusionXX_minX3 Geom3DRB_ATheta_DiffusionXX_minX3_0;
  Geom3DRB_ATheta_DiffusionXY_minX3 Geom3DRB_ATheta_DiffusionXY_minX3_0;
  Geom3DRB_ATheta_DiffusionXZ_minX3 Geom3DRB_ATheta_DiffusionXZ_minX3_0;
  Geom3DRB_ATheta_DiffusionYX_minX3 Geom3DRB_ATheta_DiffusionYX_minX3_0;
  Geom3DRB_ATheta_DiffusionYY_minX3 Geom3DRB_ATheta_DiffusionYY_minX3_0;
  Geom3DRB_ATheta_DiffusionYZ_minX3 Geom3DRB_ATheta_DiffusionYZ_minX3_0;
  Geom3DRB_ATheta_DiffusionZX_minX3 Geom3DRB_ATheta_DiffusionZX_minX3_0;
  Geom3DRB_ATheta_DiffusionZY_minX3 Geom3DRB_ATheta_DiffusionZY_minX3_0;
  Geom3DRB_ATheta_DiffusionZZ_minX3 Geom3DRB_ATheta_DiffusionZZ_minX3_0;
  Geom3DRB_ATheta_DiffusionXX_minX4 Geom3DRB_ATheta_DiffusionXX_minX4_0;
  Geom3DRB_ATheta_DiffusionXY_minX4 Geom3DRB_ATheta_DiffusionXY_minX4_0;
  Geom3DRB_ATheta_DiffusionXZ_minX4 Geom3DRB_ATheta_DiffusionXZ_minX4_0;
  Geom3DRB_ATheta_DiffusionYX_minX4 Geom3DRB_ATheta_DiffusionYX_minX4_0;
  Geom3DRB_ATheta_DiffusionYY_minX4 Geom3DRB_ATheta_DiffusionYY_minX4_0;
  Geom3DRB_ATheta_DiffusionYZ_minX4 Geom3DRB_ATheta_DiffusionYZ_minX4_0;
  Geom3DRB_ATheta_DiffusionZX_minX4 Geom3DRB_ATheta_DiffusionZX_minX4_0;
  Geom3DRB_ATheta_DiffusionZY_minX4 Geom3DRB_ATheta_DiffusionZY_minX4_0;
  Geom3DRB_ATheta_DiffusionZZ_minX4 Geom3DRB_ATheta_DiffusionZZ_minX4_0;
  Geom3DRB_ATheta_DiffusionXX_minX5 Geom3DRB_ATheta_DiffusionXX_minX5_0;
  Geom3DRB_ATheta_DiffusionXY_minX5 Geom3DRB_ATheta_DiffusionXY_minX5_0;
  Geom3DRB_ATheta_DiffusionXZ_minX5 Geom3DRB_ATheta_DiffusionXZ_minX5_0;
  Geom3DRB_ATheta_DiffusionYX_minX5 Geom3DRB_ATheta_DiffusionYX_minX5_0;
  Geom3DRB_ATheta_DiffusionYY_minX5 Geom3DRB_ATheta_DiffusionYY_minX5_0;
  Geom3DRB_ATheta_DiffusionYZ_minX5 Geom3DRB_ATheta_DiffusionYZ_minX5_0;
  Geom3DRB_ATheta_DiffusionZX_minX5 Geom3DRB_ATheta_DiffusionZX_minX5_0;
  Geom3DRB_ATheta_DiffusionZY_minX5 Geom3DRB_ATheta_DiffusionZY_minX5_0;
  Geom3DRB_ATheta_DiffusionZZ_minX5 Geom3DRB_ATheta_DiffusionZZ_minX5_0;
  Geom3DRB_ATheta_DiffusionXX_maxY1 Geom3DRB_ATheta_DiffusionXX_maxY1_0;
  Geom3DRB_ATheta_DiffusionXY_maxY1 Geom3DRB_ATheta_DiffusionXY_maxY1_0;
  Geom3DRB_ATheta_DiffusionXZ_maxY1 Geom3DRB_ATheta_DiffusionXZ_maxY1_0;
  Geom3DRB_ATheta_DiffusionYX_maxY1 Geom3DRB_ATheta_DiffusionYX_maxY1_0;
  Geom3DRB_ATheta_DiffusionYY_maxY1 Geom3DRB_ATheta_DiffusionYY_maxY1_0;
  Geom3DRB_ATheta_DiffusionYZ_maxY1 Geom3DRB_ATheta_DiffusionYZ_maxY1_0;
  Geom3DRB_ATheta_DiffusionZX_maxY1 Geom3DRB_ATheta_DiffusionZX_maxY1_0;
  Geom3DRB_ATheta_DiffusionZY_maxY1 Geom3DRB_ATheta_DiffusionZY_maxY1_0;
  Geom3DRB_ATheta_DiffusionZZ_maxY1 Geom3DRB_ATheta_DiffusionZZ_maxY1_0;
  Geom3DRB_ATheta_DiffusionXX_maxY2 Geom3DRB_ATheta_DiffusionXX_maxY2_0;
  Geom3DRB_ATheta_DiffusionXY_maxY2 Geom3DRB_ATheta_DiffusionXY_maxY2_0;
  Geom3DRB_ATheta_DiffusionXZ_maxY2 Geom3DRB_ATheta_DiffusionXZ_maxY2_0;
  Geom3DRB_ATheta_DiffusionYX_maxY2 Geom3DRB_ATheta_DiffusionYX_maxY2_0;
  Geom3DRB_ATheta_DiffusionYY_maxY2 Geom3DRB_ATheta_DiffusionYY_maxY2_0;
  Geom3DRB_ATheta_DiffusionYZ_maxY2 Geom3DRB_ATheta_DiffusionYZ_maxY2_0;
  Geom3DRB_ATheta_DiffusionZX_maxY2 Geom3DRB_ATheta_DiffusionZX_maxY2_0;
  Geom3DRB_ATheta_DiffusionZY_maxY2 Geom3DRB_ATheta_DiffusionZY_maxY2_0;
  Geom3DRB_ATheta_DiffusionZZ_maxY2 Geom3DRB_ATheta_DiffusionZZ_maxY2_0;
  Geom3DRB_ATheta_DiffusionXX_maxY3 Geom3DRB_ATheta_DiffusionXX_maxY3_0;
  Geom3DRB_ATheta_DiffusionXY_maxY3 Geom3DRB_ATheta_DiffusionXY_maxY3_0;
  Geom3DRB_ATheta_DiffusionXZ_maxY3 Geom3DRB_ATheta_DiffusionXZ_maxY3_0;
  Geom3DRB_ATheta_DiffusionYX_maxY3 Geom3DRB_ATheta_DiffusionYX_maxY3_0;
  Geom3DRB_ATheta_DiffusionYY_maxY3 Geom3DRB_ATheta_DiffusionYY_maxY3_0;
  Geom3DRB_ATheta_DiffusionYZ_maxY3 Geom3DRB_ATheta_DiffusionYZ_maxY3_0;
  Geom3DRB_ATheta_DiffusionZX_maxY3 Geom3DRB_ATheta_DiffusionZX_maxY3_0;
  Geom3DRB_ATheta_DiffusionZY_maxY3 Geom3DRB_ATheta_DiffusionZY_maxY3_0;
  Geom3DRB_ATheta_DiffusionZZ_maxY3 Geom3DRB_ATheta_DiffusionZZ_maxY3_0;
  Geom3DRB_ATheta_DiffusionXX_maxY4 Geom3DRB_ATheta_DiffusionXX_maxY4_0;
  Geom3DRB_ATheta_DiffusionXY_maxY4 Geom3DRB_ATheta_DiffusionXY_maxY4_0;
  Geom3DRB_ATheta_DiffusionXZ_maxY4 Geom3DRB_ATheta_DiffusionXZ_maxY4_0;
  Geom3DRB_ATheta_DiffusionYX_maxY4 Geom3DRB_ATheta_DiffusionYX_maxY4_0;
  Geom3DRB_ATheta_DiffusionYY_maxY4 Geom3DRB_ATheta_DiffusionYY_maxY4_0;
  Geom3DRB_ATheta_DiffusionYZ_maxY4 Geom3DRB_ATheta_DiffusionYZ_maxY4_0;
  Geom3DRB_ATheta_DiffusionZX_maxY4 Geom3DRB_ATheta_DiffusionZX_maxY4_0;
  Geom3DRB_ATheta_DiffusionZY_maxY4 Geom3DRB_ATheta_DiffusionZY_maxY4_0;
  Geom3DRB_ATheta_DiffusionZZ_maxY4 Geom3DRB_ATheta_DiffusionZZ_maxY4_0;
  Geom3DRB_ATheta_DiffusionXX_maxY5 Geom3DRB_ATheta_DiffusionXX_maxY5_0;
  Geom3DRB_ATheta_DiffusionXY_maxY5 Geom3DRB_ATheta_DiffusionXY_maxY5_0;
  Geom3DRB_ATheta_DiffusionXZ_maxY5 Geom3DRB_ATheta_DiffusionXZ_maxY5_0;
  Geom3DRB_ATheta_DiffusionYX_maxY5 Geom3DRB_ATheta_DiffusionYX_maxY5_0;
  Geom3DRB_ATheta_DiffusionYY_maxY5 Geom3DRB_ATheta_DiffusionYY_maxY5_0;
  Geom3DRB_ATheta_DiffusionYZ_maxY5 Geom3DRB_ATheta_DiffusionYZ_maxY5_0;
  Geom3DRB_ATheta_DiffusionZX_maxY5 Geom3DRB_ATheta_DiffusionZX_maxY5_0;
  Geom3DRB_ATheta_DiffusionZY_maxY5 Geom3DRB_ATheta_DiffusionZY_maxY5_0;
  Geom3DRB_ATheta_DiffusionZZ_maxY5 Geom3DRB_ATheta_DiffusionZZ_maxY5_0;
  Geom3DRB_ATheta_DiffusionXX_maxX1 Geom3DRB_ATheta_DiffusionXX_maxX1_0;
  Geom3DRB_ATheta_DiffusionXY_maxX1 Geom3DRB_ATheta_DiffusionXY_maxX1_0;
  Geom3DRB_ATheta_DiffusionXZ_maxX1 Geom3DRB_ATheta_DiffusionXZ_maxX1_0;
  Geom3DRB_ATheta_DiffusionYX_maxX1 Geom3DRB_ATheta_DiffusionYX_maxX1_0;
  Geom3DRB_ATheta_DiffusionYY_maxX1 Geom3DRB_ATheta_DiffusionYY_maxX1_0;
  Geom3DRB_ATheta_DiffusionYZ_maxX1 Geom3DRB_ATheta_DiffusionYZ_maxX1_0;
  Geom3DRB_ATheta_DiffusionZX_maxX1 Geom3DRB_ATheta_DiffusionZX_maxX1_0;
  Geom3DRB_ATheta_DiffusionZY_maxX1 Geom3DRB_ATheta_DiffusionZY_maxX1_0;
  Geom3DRB_ATheta_DiffusionZZ_maxX1 Geom3DRB_ATheta_DiffusionZZ_maxX1_0;
  Geom3DRB_ATheta_DiffusionXX_maxX2 Geom3DRB_ATheta_DiffusionXX_maxX2_0;
  Geom3DRB_ATheta_DiffusionXY_maxX2 Geom3DRB_ATheta_DiffusionXY_maxX2_0;
  Geom3DRB_ATheta_DiffusionXZ_maxX2 Geom3DRB_ATheta_DiffusionXZ_maxX2_0;
  Geom3DRB_ATheta_DiffusionYX_maxX2 Geom3DRB_ATheta_DiffusionYX_maxX2_0;
  Geom3DRB_ATheta_DiffusionYY_maxX2 Geom3DRB_ATheta_DiffusionYY_maxX2_0;
  Geom3DRB_ATheta_DiffusionYZ_maxX2 Geom3DRB_ATheta_DiffusionYZ_maxX2_0;
  Geom3DRB_ATheta_DiffusionZX_maxX2 Geom3DRB_ATheta_DiffusionZX_maxX2_0;
  Geom3DRB_ATheta_DiffusionZY_maxX2 Geom3DRB_ATheta_DiffusionZY_maxX2_0;
  Geom3DRB_ATheta_DiffusionZZ_maxX2 Geom3DRB_ATheta_DiffusionZZ_maxX2_0;
  Geom3DRB_ATheta_DiffusionXX_maxX3 Geom3DRB_ATheta_DiffusionXX_maxX3_0;
  Geom3DRB_ATheta_DiffusionXY_maxX3 Geom3DRB_ATheta_DiffusionXY_maxX3_0;
  Geom3DRB_ATheta_DiffusionXZ_maxX3 Geom3DRB_ATheta_DiffusionXZ_maxX3_0;
  Geom3DRB_ATheta_DiffusionYX_maxX3 Geom3DRB_ATheta_DiffusionYX_maxX3_0;
  Geom3DRB_ATheta_DiffusionYY_maxX3 Geom3DRB_ATheta_DiffusionYY_maxX3_0;
  Geom3DRB_ATheta_DiffusionYZ_maxX3 Geom3DRB_ATheta_DiffusionYZ_maxX3_0;
  Geom3DRB_ATheta_DiffusionZX_maxX3 Geom3DRB_ATheta_DiffusionZX_maxX3_0;
  Geom3DRB_ATheta_DiffusionZY_maxX3 Geom3DRB_ATheta_DiffusionZY_maxX3_0;
  Geom3DRB_ATheta_DiffusionZZ_maxX3 Geom3DRB_ATheta_DiffusionZZ_maxX3_0;
  Geom3DRB_ATheta_DiffusionXX_maxX4 Geom3DRB_ATheta_DiffusionXX_maxX4_0;
  Geom3DRB_ATheta_DiffusionXY_maxX4 Geom3DRB_ATheta_DiffusionXY_maxX4_0;
  Geom3DRB_ATheta_DiffusionXZ_maxX4 Geom3DRB_ATheta_DiffusionXZ_maxX4_0;
  Geom3DRB_ATheta_DiffusionYX_maxX4 Geom3DRB_ATheta_DiffusionYX_maxX4_0;
  Geom3DRB_ATheta_DiffusionYY_maxX4 Geom3DRB_ATheta_DiffusionYY_maxX4_0;
  Geom3DRB_ATheta_DiffusionYZ_maxX4 Geom3DRB_ATheta_DiffusionYZ_maxX4_0;
  Geom3DRB_ATheta_DiffusionZX_maxX4 Geom3DRB_ATheta_DiffusionZX_maxX4_0;
  Geom3DRB_ATheta_DiffusionZY_maxX4 Geom3DRB_ATheta_DiffusionZY_maxX4_0;
  Geom3DRB_ATheta_DiffusionZZ_maxX4 Geom3DRB_ATheta_DiffusionZZ_maxX4_0;
  Geom3DRB_ATheta_DiffusionXX_maxX5 Geom3DRB_ATheta_DiffusionXX_maxX5_0;
  Geom3DRB_ATheta_DiffusionXY_maxX5 Geom3DRB_ATheta_DiffusionXY_maxX5_0;
  Geom3DRB_ATheta_DiffusionXZ_maxX5 Geom3DRB_ATheta_DiffusionXZ_maxX5_0;
  Geom3DRB_ATheta_DiffusionYX_maxX5 Geom3DRB_ATheta_DiffusionYX_maxX5_0;
  Geom3DRB_ATheta_DiffusionYY_maxX5 Geom3DRB_ATheta_DiffusionYY_maxX5_0;
  Geom3DRB_ATheta_DiffusionYZ_maxX5 Geom3DRB_ATheta_DiffusionYZ_maxX5_0;
  Geom3DRB_ATheta_DiffusionZX_maxX5 Geom3DRB_ATheta_DiffusionZX_maxX5_0;
  Geom3DRB_ATheta_DiffusionZY_maxX5 Geom3DRB_ATheta_DiffusionZY_maxX5_0;
  Geom3DRB_ATheta_DiffusionZZ_maxX5 Geom3DRB_ATheta_DiffusionZZ_maxX5_0;
  Geom3DRB_ATheta_DiffusionXX_minY1 Geom3DRB_ATheta_DiffusionXX_minY1_0;
  Geom3DRB_ATheta_DiffusionXY_minY1 Geom3DRB_ATheta_DiffusionXY_minY1_0;
  Geom3DRB_ATheta_DiffusionXZ_minY1 Geom3DRB_ATheta_DiffusionXZ_minY1_0;
  Geom3DRB_ATheta_DiffusionYX_minY1 Geom3DRB_ATheta_DiffusionYX_minY1_0;
  Geom3DRB_ATheta_DiffusionYY_minY1 Geom3DRB_ATheta_DiffusionYY_minY1_0;
  Geom3DRB_ATheta_DiffusionYZ_minY1 Geom3DRB_ATheta_DiffusionYZ_minY1_0;
  Geom3DRB_ATheta_DiffusionZX_minY1 Geom3DRB_ATheta_DiffusionZX_minY1_0;
  Geom3DRB_ATheta_DiffusionZY_minY1 Geom3DRB_ATheta_DiffusionZY_minY1_0;
  Geom3DRB_ATheta_DiffusionZZ_minY1 Geom3DRB_ATheta_DiffusionZZ_minY1_0;
  Geom3DRB_ATheta_DiffusionXX_minY2 Geom3DRB_ATheta_DiffusionXX_minY2_0;
  Geom3DRB_ATheta_DiffusionXY_minY2 Geom3DRB_ATheta_DiffusionXY_minY2_0;
  Geom3DRB_ATheta_DiffusionXZ_minY2 Geom3DRB_ATheta_DiffusionXZ_minY2_0;
  Geom3DRB_ATheta_DiffusionYX_minY2 Geom3DRB_ATheta_DiffusionYX_minY2_0;
  Geom3DRB_ATheta_DiffusionYY_minY2 Geom3DRB_ATheta_DiffusionYY_minY2_0;
  Geom3DRB_ATheta_DiffusionYZ_minY2 Geom3DRB_ATheta_DiffusionYZ_minY2_0;
  Geom3DRB_ATheta_DiffusionZX_minY2 Geom3DRB_ATheta_DiffusionZX_minY2_0;
  Geom3DRB_ATheta_DiffusionZY_minY2 Geom3DRB_ATheta_DiffusionZY_minY2_0;
  Geom3DRB_ATheta_DiffusionZZ_minY2 Geom3DRB_ATheta_DiffusionZZ_minY2_0;
  Geom3DRB_ATheta_DiffusionXX_minY3 Geom3DRB_ATheta_DiffusionXX_minY3_0;
  Geom3DRB_ATheta_DiffusionXY_minY3 Geom3DRB_ATheta_DiffusionXY_minY3_0;
  Geom3DRB_ATheta_DiffusionXZ_minY3 Geom3DRB_ATheta_DiffusionXZ_minY3_0;
  Geom3DRB_ATheta_DiffusionYX_minY3 Geom3DRB_ATheta_DiffusionYX_minY3_0;
  Geom3DRB_ATheta_DiffusionYY_minY3 Geom3DRB_ATheta_DiffusionYY_minY3_0;
  Geom3DRB_ATheta_DiffusionYZ_minY3 Geom3DRB_ATheta_DiffusionYZ_minY3_0;
  Geom3DRB_ATheta_DiffusionZX_minY3 Geom3DRB_ATheta_DiffusionZX_minY3_0;
  Geom3DRB_ATheta_DiffusionZY_minY3 Geom3DRB_ATheta_DiffusionZY_minY3_0;
  Geom3DRB_ATheta_DiffusionZZ_minY3 Geom3DRB_ATheta_DiffusionZZ_minY3_0;
  Geom3DRB_ATheta_DiffusionXX_minY4 Geom3DRB_ATheta_DiffusionXX_minY4_0;
  Geom3DRB_ATheta_DiffusionXY_minY4 Geom3DRB_ATheta_DiffusionXY_minY4_0;
  Geom3DRB_ATheta_DiffusionXZ_minY4 Geom3DRB_ATheta_DiffusionXZ_minY4_0;
  Geom3DRB_ATheta_DiffusionYX_minY4 Geom3DRB_ATheta_DiffusionYX_minY4_0;
  Geom3DRB_ATheta_DiffusionYY_minY4 Geom3DRB_ATheta_DiffusionYY_minY4_0;
  Geom3DRB_ATheta_DiffusionYZ_minY4 Geom3DRB_ATheta_DiffusionYZ_minY4_0;
  Geom3DRB_ATheta_DiffusionZX_minY4 Geom3DRB_ATheta_DiffusionZX_minY4_0;
  Geom3DRB_ATheta_DiffusionZY_minY4 Geom3DRB_ATheta_DiffusionZY_minY4_0;
  Geom3DRB_ATheta_DiffusionZZ_minY4 Geom3DRB_ATheta_DiffusionZZ_minY4_0;
  Geom3DRB_ATheta_DiffusionXX_minY5 Geom3DRB_ATheta_DiffusionXX_minY5_0;
  Geom3DRB_ATheta_DiffusionXY_minY5 Geom3DRB_ATheta_DiffusionXY_minY5_0;
  Geom3DRB_ATheta_DiffusionXZ_minY5 Geom3DRB_ATheta_DiffusionXZ_minY5_0;
  Geom3DRB_ATheta_DiffusionYX_minY5 Geom3DRB_ATheta_DiffusionYX_minY5_0;
  Geom3DRB_ATheta_DiffusionYY_minY5 Geom3DRB_ATheta_DiffusionYY_minY5_0;
  Geom3DRB_ATheta_DiffusionYZ_minY5 Geom3DRB_ATheta_DiffusionYZ_minY5_0;
  Geom3DRB_ATheta_DiffusionZX_minY5 Geom3DRB_ATheta_DiffusionZX_minY5_0;
  Geom3DRB_ATheta_DiffusionZY_minY5 Geom3DRB_ATheta_DiffusionZY_minY5_0;
  Geom3DRB_ATheta_DiffusionZZ_minY5 Geom3DRB_ATheta_DiffusionZZ_minY5_0;
  Geom3DRB_ATheta_DiffusionXX_minZ1 Geom3DRB_ATheta_DiffusionXX_minZ1_0;
  Geom3DRB_ATheta_DiffusionXY_minZ1 Geom3DRB_ATheta_DiffusionXY_minZ1_0;
  Geom3DRB_ATheta_DiffusionXZ_minZ1 Geom3DRB_ATheta_DiffusionXZ_minZ1_0;
  Geom3DRB_ATheta_DiffusionYX_minZ1 Geom3DRB_ATheta_DiffusionYX_minZ1_0;
  Geom3DRB_ATheta_DiffusionYY_minZ1 Geom3DRB_ATheta_DiffusionYY_minZ1_0;
  Geom3DRB_ATheta_DiffusionYZ_minZ1 Geom3DRB_ATheta_DiffusionYZ_minZ1_0;
  Geom3DRB_ATheta_DiffusionZX_minZ1 Geom3DRB_ATheta_DiffusionZX_minZ1_0;
  Geom3DRB_ATheta_DiffusionZY_minZ1 Geom3DRB_ATheta_DiffusionZY_minZ1_0;
  Geom3DRB_ATheta_DiffusionZZ_minZ1 Geom3DRB_ATheta_DiffusionZZ_minZ1_0;
  Geom3DRB_ATheta_DiffusionXX_minZ2 Geom3DRB_ATheta_DiffusionXX_minZ2_0;
  Geom3DRB_ATheta_DiffusionXY_minZ2 Geom3DRB_ATheta_DiffusionXY_minZ2_0;
  Geom3DRB_ATheta_DiffusionXZ_minZ2 Geom3DRB_ATheta_DiffusionXZ_minZ2_0;
  Geom3DRB_ATheta_DiffusionYX_minZ2 Geom3DRB_ATheta_DiffusionYX_minZ2_0;
  Geom3DRB_ATheta_DiffusionYY_minZ2 Geom3DRB_ATheta_DiffusionYY_minZ2_0;
  Geom3DRB_ATheta_DiffusionYZ_minZ2 Geom3DRB_ATheta_DiffusionYZ_minZ2_0;
  Geom3DRB_ATheta_DiffusionZX_minZ2 Geom3DRB_ATheta_DiffusionZX_minZ2_0;
  Geom3DRB_ATheta_DiffusionZY_minZ2 Geom3DRB_ATheta_DiffusionZY_minZ2_0;
  Geom3DRB_ATheta_DiffusionZZ_minZ2 Geom3DRB_ATheta_DiffusionZZ_minZ2_0;
  Geom3DRB_ATheta_DiffusionXX_minZ3 Geom3DRB_ATheta_DiffusionXX_minZ3_0;
  Geom3DRB_ATheta_DiffusionXY_minZ3 Geom3DRB_ATheta_DiffusionXY_minZ3_0;
  Geom3DRB_ATheta_DiffusionXZ_minZ3 Geom3DRB_ATheta_DiffusionXZ_minZ3_0;
  Geom3DRB_ATheta_DiffusionYX_minZ3 Geom3DRB_ATheta_DiffusionYX_minZ3_0;
  Geom3DRB_ATheta_DiffusionYY_minZ3 Geom3DRB_ATheta_DiffusionYY_minZ3_0;
  Geom3DRB_ATheta_DiffusionYZ_minZ3 Geom3DRB_ATheta_DiffusionYZ_minZ3_0;
  Geom3DRB_ATheta_DiffusionZX_minZ3 Geom3DRB_ATheta_DiffusionZX_minZ3_0;
  Geom3DRB_ATheta_DiffusionZY_minZ3 Geom3DRB_ATheta_DiffusionZY_minZ3_0;
  Geom3DRB_ATheta_DiffusionZZ_minZ3 Geom3DRB_ATheta_DiffusionZZ_minZ3_0;
  Geom3DRB_ATheta_DiffusionXX_minZ4 Geom3DRB_ATheta_DiffusionXX_minZ4_0;
  Geom3DRB_ATheta_DiffusionXY_minZ4 Geom3DRB_ATheta_DiffusionXY_minZ4_0;
  Geom3DRB_ATheta_DiffusionXZ_minZ4 Geom3DRB_ATheta_DiffusionXZ_minZ4_0;
  Geom3DRB_ATheta_DiffusionYX_minZ4 Geom3DRB_ATheta_DiffusionYX_minZ4_0;
  Geom3DRB_ATheta_DiffusionYY_minZ4 Geom3DRB_ATheta_DiffusionYY_minZ4_0;
  Geom3DRB_ATheta_DiffusionYZ_minZ4 Geom3DRB_ATheta_DiffusionYZ_minZ4_0;
  Geom3DRB_ATheta_DiffusionZX_minZ4 Geom3DRB_ATheta_DiffusionZX_minZ4_0;
  Geom3DRB_ATheta_DiffusionZY_minZ4 Geom3DRB_ATheta_DiffusionZY_minZ4_0;
  Geom3DRB_ATheta_DiffusionZZ_minZ4 Geom3DRB_ATheta_DiffusionZZ_minZ4_0;
  Geom3DRB_ATheta_DiffusionXX_minZ5 Geom3DRB_ATheta_DiffusionXX_minZ5_0;
  Geom3DRB_ATheta_DiffusionXY_minZ5 Geom3DRB_ATheta_DiffusionXY_minZ5_0;
  Geom3DRB_ATheta_DiffusionXZ_minZ5 Geom3DRB_ATheta_DiffusionXZ_minZ5_0;
  Geom3DRB_ATheta_DiffusionYX_minZ5 Geom3DRB_ATheta_DiffusionYX_minZ5_0;
  Geom3DRB_ATheta_DiffusionYY_minZ5 Geom3DRB_ATheta_DiffusionYY_minZ5_0;
  Geom3DRB_ATheta_DiffusionYZ_minZ5 Geom3DRB_ATheta_DiffusionYZ_minZ5_0;
  Geom3DRB_ATheta_DiffusionZX_minZ5 Geom3DRB_ATheta_DiffusionZX_minZ5_0;
  Geom3DRB_ATheta_DiffusionZY_minZ5 Geom3DRB_ATheta_DiffusionZY_minZ5_0;
  Geom3DRB_ATheta_DiffusionZZ_minZ5 Geom3DRB_ATheta_DiffusionZZ_minZ5_0;
  Geom3DRB_ATheta_DiffusionXX_VesselCyl Geom3DRB_ATheta_DiffusionXX_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionXY_VesselCyl Geom3DRB_ATheta_DiffusionXY_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionXZ_VesselCyl Geom3DRB_ATheta_DiffusionXZ_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionYX_VesselCyl Geom3DRB_ATheta_DiffusionYX_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionYY_VesselCyl Geom3DRB_ATheta_DiffusionYY_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionYZ_VesselCyl Geom3DRB_ATheta_DiffusionYZ_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionZX_VesselCyl Geom3DRB_ATheta_DiffusionZX_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionZY_VesselCyl Geom3DRB_ATheta_DiffusionZY_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionZZ_VesselCyl Geom3DRB_ATheta_DiffusionZZ_VesselCyl_0;
  Geom3DRB_ATheta_DiffusionXX_BoundingBox Geom3DRB_ATheta_DiffusionXX_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionXY_BoundingBox Geom3DRB_ATheta_DiffusionXY_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionXZ_BoundingBox Geom3DRB_ATheta_DiffusionXZ_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionYX_BoundingBox Geom3DRB_ATheta_DiffusionYX_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionYY_BoundingBox Geom3DRB_ATheta_DiffusionYY_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionYZ_BoundingBox Geom3DRB_ATheta_DiffusionYZ_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionZX_BoundingBox Geom3DRB_ATheta_DiffusionZX_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionZY_BoundingBox Geom3DRB_ATheta_DiffusionZY_BoundingBox_0;
  Geom3DRB_ATheta_DiffusionZZ_BoundingBox Geom3DRB_ATheta_DiffusionZZ_BoundingBox_0;
  RBTheta _rb_theta;
};

//------------------------------
#endif // DWARFELEPHANTGEOM3DRBTHETAEXPANSION_RFA_H